module.exports = [
    {
      name: "Scooby-Doo",
      image: "/images/Scoob.jpg",
      breed: "Great Dane",
      renown: "Cartoon",
      description: "One of Hanna-Barbera's most iconic characters, debuting in 1969 in Scooby Doo Where Are You! His name comes from scat lyrics at the end of Frank Sinatra's song 'Strangers in the Night'. In designing the character, Iwao Takamoto studied Great Danes and then gave Scooby the opposite traits.",
      deceased: false,
    },
    {
      name: "Terry",
      image: "/images/Terry.jpg",
      breed: "Cairn Terrier",
      renown: "Film",
      description: "Terry (November 17, 1933 – September 1, 1945) was a female Cairn Terrier performer who appeared in many different movies, most famously as Toto in the film The Wizard of Oz (1939).",
      deceased: true,
    },
    {
      name: "Blue the Dog",
      image: "/images/Blue_the_dog.jpg",
      breed: "unkown",
      renown: "Cartoon",
      description: "(born 1994; age 2 in the show; age today 28), is a cartoon dog that lives with a young man named Steve (or Joe), and likes to play a game called Blue's Clues (game). She is seen in the popular Nick Jr TV series Blue's Clues.",
      deceased: false,
    },
    {
      name: "Doug the Pug",
      image: "/images/Doug.jpg",
      breed: "pug",
      renown: "Social Media",
      description: "Perhaps the most well-known pug in the world, Doug the Pug boasts 2.9M Instagram followers. The Nashville based dog’s Instagram success has led to several calendars, a New York Times best-selling book, and his own merchandise.",
      deceased: false,
    },
    {
      name: "Chris",
      image: "/images/Chris.jpg",
      breed: "St. Bernard",
      renown: "Film",
      description: "Chris is an actor, known for Beethoven (1992) and The 11th Annual Genesis Awards (1997).",
      deceased: true,
    },
    {
      name: "Pal",
      image: "/images/Pal.jpg",
      breed: "Rough Collie",
      renown: "TV",
      description: "June 4, 1940 – June 18, 1958) was a male Rough Collie performer and the first in a line of such dogs to portray the fictional female collie Lassie in film, on radio, and on television.",
      deceased: true,
    },
    {
      name: "Moose",
      image: "/images/Moose.jpg",
      breed: "Jack Russell Terrier",
      renown: "TV",
      description: "(December 24, 1990 – June 22, 2006) was a wire-hair Jack Russell Terrier[4] who portrayed Eddie Crane on the American television sitcom Frasier.",
      deceased: true,
    },
    {
      name: "Jiff Pom",
      image: "/images/Jiff_pom.jpg",
      breed: "Pomeranian",
      renown: "Social Media",
      description: "Jiff Pom, a Pomeranian pup, is the most followed dog on all of Instagram with 9.9M followers. Jiff Pom has continued building his widespread online popularity as a top TikTok influencer with 20.8 million followers.",
      deceased: false,
    },
  ]